[package]
name = "prox"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1.0.0-rc.3", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
