listen = "0.0.0.0:443"
cert_chain = "/etc/letsencrypt/live/files.chxry.me-0001/fullchain.pem"
private_key = "/etc/letsencrypt/live/files.chxry.me-0001/privkey.pem"

[services]
"files.chxry.me" = "0.0.0.0:3000"
"test.chxry.me" = "0.0.0.0:4000"

